kind: pipeline
type: kubernetes
name: drone
service_account_name: default

metadata:
  namespace: drone

steps:
- name: set-tag
  image: python:3.9
  environment:
    DRONE: "true"
  commands:
  - echo -n v$DRONE_BUILD_NUMBER > .tags
  - cat .tags
- name: docker-build
  image: plugins/docker
  when:
    branch:
    - main
    event:
      exclude:
      - pull_request
  settings:
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: wildflowerschools/wf-drone-slim-template
- name: docker-build-slim
  image: docker:dind
  environment:
    DRONE: "true"
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
    TAG: wildflowerschools/wf-drone-slim-template:v$DRONE_BUILD_NUMBER
  commands:
    - sleep 5 # give docker enough time to start
    - docker ps -a
    - docker images
    - docker run -e dslim/docker-slim build --dockerfile Dockerfile --tag $env:TAG
    - docker login -u $env:USERNAME -p $env:PASSWORD
    - docker push ${env:TAG}.slim
    - docker rmi  ${env:TAG}.slim
  volumes:
    - name: dockersock
      path: /var/run

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}